import type { Metadata } from "next";
import "./css/globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer"
import { spaceGrotesk } from "@/app/fonts";
import { Providers } from "@/app/Providers";

export const metadata: Metadata = {
  title: "create next app",
  description: "Generated by create next app",
};

<link rel="icon" href="/icon.png" sizes="any" />

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </ Providers>
      </body>
    </html>
  );
}
