import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import { spaceGrotesk } from "./fonts";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "create next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </ Providers>
      </body>
    </html>
  );
}
